language: rust
rust:
  - stable

os: linux
dist: bionic

addons:
  apt:
    packages:
      - gcc-arm-linux-gnueabihf
      - libc6-armhf-cross
      - libc6-dev-armhf-cross
      - binutils-arm-linux-gnueabihf

before_script:
  - rustup target add armv7-unknown-linux-musleabihf
  - |
    echo "[target.armv7-unknown-linux-musleabihf]" > ~/.cargo/config
    echo "linker = \"arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config

script:
  - sed -i "s/version = \"0.0.0-snapshot\"/version = \"${TRAVIS_TAG#v}\"/g" Cargo.toml
  - cargo install cargo-deb
  - cargo build --release --target=armv7-unknown-linux-musleabihf
  - cargo deb --target=armv7-unknown-linux-musleabihf
  - ls target/armv7-unknown-linux-musleabihf/debian/*.deb
  #- cargo test --target=armv7-unknown-linux-musleabihf

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - "target/armv7-unknown-linux-musleabihf/debian/tc2-agent_${TRAVIS_TAG#v}_armhf.deb"
  skip_cleanup: true
  on:
    tags: true
