language: rust
rust:
  - stable

os: linux
dist: focal

addons:
  apt:
    packages:
      - gcc-arm-linux-gnueabihf
      - libc6-armhf-cross
      - libc6-dev-armhf-cross
      - binutils-arm-linux-gnueabihf

before_script:
  - rustup target add armv7-unknown-linux-musleabihf
  - |
    echo "[target.armv7-unknown-linux-musleabihf]" > ~/.cargo/config
    echo "linker = \"arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config

script:
  - if [ -n "$TRAVIS_TAG" ]; then sed -i "s/version = \"0.0.0-snapshot\"/version = \"${TRAVIS_TAG#v}\"/g" Cargo.toml; fi
  - cargo install cargo-deb
  - cargo build --release --target=armv7-unknown-linux-musleabihf
  - wget -O _releases/tc2-firmware https://github.com/TheCacophonyProject/tc2-firmware/releases/download/v0.1.6/tc2-firmware
  - cargo deb --target=armv7-unknown-linux-musleabihf --output tc2-agent_${TRAVIS_TAG#v}_armhf.deb

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - "tc2-agent_${TRAVIS_TAG#v}_armhf.deb"
  skip_cleanup: true
  on:
    tags: true
