[package]
name = "tc2-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
framebuffer = "0.3.1"
bmp = "0.5.0"
rppal = "0.14.1"
chrono = "0.4.24"
byteorder = { version = "^1.3", default-features = false }
thread-priority = "0.13.1"
argh = "0.1.10"
mdns-sd = "0.7.3"


[target.armv7-unknown-linux-musleabihf]
# applies to target-specific builds

# rPi4
#rustflags = "-C target-cpu=cortex-a72"

# rPi3
rustflags = "-C target-cpu=cortex-a53"
